alias tmux='tmux -f $HOME/.tmux.conf'
alias tmuxs='tmux-session save'
alias tmuxr='tmux-session restore'
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."
alias l='ls -l'
alias ll='ls -la'
